# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'design.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from cmath import e
from traceback import print_tb
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QFileDialog, QMessageBox
import main

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1414, 733)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setStyleSheet("background-color: rgb(33, 0, 124)")
        self.tabWidget.setObjectName("tabWidget")
        self.Home = QtWidgets.QWidget()
        self.Home.setObjectName("Home")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.Home)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_15 = QtWidgets.QLabel(self.Home)
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap("C:/Users/Billal/Pictures/Capture10.PNG"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_3.addWidget(self.label_15)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.Home)
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("C:/Users/Billal/Downloads/undraw_Slider_re_ch7w.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.horizontalLayout_3.addLayout(self.gridLayout_2)
        self.tabWidget.addTab(self.Home, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_2)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.groupBox = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Ignored)
        self.gridLayout_11.addItem(spacerItem1, 9, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem2, 3, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem3, 7, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem4, 5, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem5, 10, 0, 1, 1)
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.label_9 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_18.addWidget(self.label_9)
        self.checkBox_31 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_31.setObjectName("checkBox_31")
        self.horizontalLayout_18.addWidget(self.checkBox_31)
        self.checkBox_32 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_32.setObjectName("checkBox_32")
        self.horizontalLayout_18.addWidget(self.checkBox_32)
        self.checkBox_33 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_33.setObjectName("checkBox_33")
        self.horizontalLayout_18.addWidget(self.checkBox_33)
        self.checkBox_34 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_34.setObjectName("checkBox_34")
        self.horizontalLayout_18.addWidget(self.checkBox_34)
        self.checkBox_35 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_35.setObjectName("checkBox_35")
        self.horizontalLayout_18.addWidget(self.checkBox_35)
        self.gridLayout_11.addLayout(self.horizontalLayout_18, 4, 0, 1, 1)
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.label_10 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_19.addWidget(self.label_10)
        self.checkBox_36 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_36.setObjectName("checkBox_36")
        self.horizontalLayout_19.addWidget(self.checkBox_36)
        self.checkBox_37 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_37.setObjectName("checkBox_37")
        self.horizontalLayout_19.addWidget(self.checkBox_37)
        self.checkBox_38 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_38.setObjectName("checkBox_38")
        self.horizontalLayout_19.addWidget(self.checkBox_38)
        self.checkBox_39 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_39.setObjectName("checkBox_39")
        self.horizontalLayout_19.addWidget(self.checkBox_39)
        self.checkBox_40 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_40.setObjectName("checkBox_40")
        self.horizontalLayout_19.addWidget(self.checkBox_40)
        self.gridLayout_11.addLayout(self.horizontalLayout_19, 11, 0, 1, 1)
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.label_11 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_20.addWidget(self.label_11)
        self.checkBox_41 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_41.setObjectName("checkBox_41")
        self.horizontalLayout_20.addWidget(self.checkBox_41)
        self.checkBox_42 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_42.setObjectName("checkBox_42")
        self.horizontalLayout_20.addWidget(self.checkBox_42)
        self.checkBox_43 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_43.setObjectName("checkBox_43")
        self.horizontalLayout_20.addWidget(self.checkBox_43)
        self.checkBox_44 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_44.setObjectName("checkBox_44")
        self.horizontalLayout_20.addWidget(self.checkBox_44)
        self.checkBox_45 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_45.setObjectName("checkBox_45")
        self.horizontalLayout_20.addWidget(self.checkBox_45)
        self.gridLayout_11.addLayout(self.horizontalLayout_20, 0, 0, 1, 1)
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.label_12 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_21.addWidget(self.label_12)
        self.checkBox_46 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_46.setObjectName("checkBox_46")
        self.horizontalLayout_21.addWidget(self.checkBox_46)
        self.checkBox_47 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_47.setObjectName("checkBox_47")
        self.horizontalLayout_21.addWidget(self.checkBox_47)
        self.checkBox_48 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_48.setObjectName("checkBox_48")
        self.horizontalLayout_21.addWidget(self.checkBox_48)
        self.checkBox_49 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_49.setObjectName("checkBox_49")
        self.horizontalLayout_21.addWidget(self.checkBox_49)
        self.checkBox_50 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_50.setObjectName("checkBox_50")
        self.horizontalLayout_21.addWidget(self.checkBox_50)
        self.gridLayout_11.addLayout(self.horizontalLayout_21, 6, 0, 1, 1)
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.label_13 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_22.addWidget(self.label_13)
        self.checkBox_51 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_51.setObjectName("checkBox_51")
        self.horizontalLayout_22.addWidget(self.checkBox_51)
        self.checkBox_52 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_52.setObjectName("checkBox_52")
        self.horizontalLayout_22.addWidget(self.checkBox_52)
        self.checkBox_53 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_53.setObjectName("checkBox_53")
        self.horizontalLayout_22.addWidget(self.checkBox_53)
        self.checkBox_54 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_54.setObjectName("checkBox_54")
        self.horizontalLayout_22.addWidget(self.checkBox_54)
        self.checkBox_55 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_55.setObjectName("checkBox_55")
        self.horizontalLayout_22.addWidget(self.checkBox_55)
        self.gridLayout_11.addLayout(self.horizontalLayout_22, 2, 0, 1, 1)
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.label_14 = QtWidgets.QLabel(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_14.sizePolicy().hasHeightForWidth())
        self.label_14.setSizePolicy(sizePolicy)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_23.addWidget(self.label_14)
        self.checkBox_56 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_56.setObjectName("checkBox_56")
        self.horizontalLayout_23.addWidget(self.checkBox_56)
        self.checkBox_57 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_57.setObjectName("checkBox_57")
        self.horizontalLayout_23.addWidget(self.checkBox_57)
        self.checkBox_58 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_58.setObjectName("checkBox_58")
        self.horizontalLayout_23.addWidget(self.checkBox_58)
        self.checkBox_59 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_59.setObjectName("checkBox_59")
        self.horizontalLayout_23.addWidget(self.checkBox_59)
        self.checkBox_60 = QtWidgets.QCheckBox(self.groupBox)
        self.checkBox_60.setObjectName("checkBox_60")
        self.horizontalLayout_23.addWidget(self.checkBox_60)
        self.gridLayout_11.addLayout(self.horizontalLayout_23, 8, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_11, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox, 2, 0, 1, 1)
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_2)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_3)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.label_8 = QtWidgets.QLabel(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_17.addWidget(self.label_8)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem6)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox_3)
        self.spinBox.setObjectName("spinBox")
        self.horizontalLayout_17.addWidget(self.spinBox)
        spacerItem7 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem7)
        self.gridLayout_5.addLayout(self.horizontalLayout_17, 0, 0, 1, 1)
        self.gridLayout_3.addWidget(self.groupBox_3, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem8)
        self.pushButton_2 = QtWidgets.QPushButton(self.tab_2)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_2.addWidget(self.pushButton_2)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem9)
        self.pushButton = QtWidgets.QPushButton(self.tab_2)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout_2.addWidget(self.pushButton)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem10)
        self.gridLayout_3.addLayout(self.horizontalLayout_2, 4, 0, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem11, 0, 0, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_3.addItem(spacerItem12, 3, 0, 1, 1)
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.spinBox.setMaximum(20000)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1414, 21))
        self.menubar.setObjectName("menubar")
        self.menuFiles = QtWidgets.QMenu(self.menubar)
        self.menuFiles.setObjectName("menuFiles")

        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuFiles.addAction(self.actionOpen)
        self.menuFiles.addAction(self.actionExit)
        self.menubar.addAction(self.menuFiles.menuAction())

        self.label_11.setAlignment(QtCore.Qt.AlignRight)
        self.label_12.setAlignment(QtCore.Qt.AlignRight)
        self.label_13.setAlignment(QtCore.Qt.AlignRight)
        self.label_9.setAlignment(QtCore.Qt.AlignRight)
        self.label_14.setAlignment(QtCore.Qt.AlignRight)
        self.label_10.setAlignment(QtCore.Qt.AlignRight)
        self.label_8.setStyleSheet("margin-left:92px")

        buttonStyle = "QPushButton{height: 50px; background-color: qlineargradient(spread:pad, x1:0.136364, y1:0.568, x2:0.972, y2:0.272727, stop:0 rgba(0, 211, 230, 255), stop:1 rgba(62, 91, 210, 255)); border-radius: 20px; font-size:20px;} QPushButton:hover{background-color: qlineargradient(spread:pad, x1:0.136364, y1:0.568, x2:0.972, y2:0.272727, stop:0 rgba(62, 91, 210, 255), stop:1 rgba(0, 211, 230, 255))}"

        self.spinBox.setStyleSheet("color: white; border: 1px solid white; border-radius:5px; height: 25px; font-size: 18px;")

        self.pushButton.setStyleSheet(buttonStyle)
        self.pushButton_2.setStyleSheet(buttonStyle)

        def confirmationPopup(self, title, text, icon):
            msg = QMessageBox()
            msg.setWindowTitle(title)
            msg.setText(text)
            msg.setIcon(icon)
            btnYes = QtWidgets.QPushButton(msg)
            btnYes.setText("Yes")
            btnNo = QtWidgets.QPushButton(msg)
            btnNo.setText("No")
            msg.addButton(btnYes, msg.ButtonRole.ActionRole)
            msg.addButton(btnNo, msg.ButtonRole.ActionRole)
            msg.exec()
            res = msg.clickedButton().text()

            return res

        def close(self):
            if(confirmationPopup(self, "Confirmation", "Do you really wanna close the application ?", QMessageBox.Icon.Question) == "Yes"):
                sys.exit(app.exec())

        self.actionExit.triggered.connect(lambda: close(self))


        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        # Variables
        self.threshold = 0
        self.right = []
        self.left = []
        self.erase = []
        self.showPointer = []
        self.draw = []
        self.changeColor = []
        self.path = -1



        def open_file(self):
            self.path = QtWidgets.QFileDialog.getExistingDirectory(None, 'Select project folder:', 'F:\\', QtWidgets.QFileDialog.ShowDirsOnly)
            if self.path == ('', ''):
                self.path = -1

        # define CSS loader
        def CssLoader(filename):
            with open(filename, 'r') as rd:
                content = rd.read()
                rd.close()
            return content

        # Import CSS file
        MainWindow.setStyleSheet(CssLoader('css/styles.css'))

        # Process
        self.pushButton_2.clicked.connect(self.process)
        self.pushButton.clicked.connect(self.default)

        # Open File
        self.actionOpen.triggered.connect(lambda: open_file(self))


    def warningPopup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Warning !")
        msg.setText("Please select a directory, or verify that the folder is not empty or it contains images !")
        msg.setIcon(QMessageBox.Icon.Warning)

        msg.exec()

    def process(self):
        self.right = self.checkBoxToList([self.checkBox_41, self.checkBox_42, self.checkBox_43, self.checkBox_44, self.checkBox_45])
        self.left = self.checkBoxToList([self.checkBox_51, self.checkBox_52, self.checkBox_53, self.checkBox_54, self.checkBox_55])
        self.erase = self.checkBoxToList([self.checkBox_56, self.checkBox_57, self.checkBox_58, self.checkBox_59, self.checkBox_60])
        self.showPointer = self.checkBoxToList([self.checkBox_31, self.checkBox_32, self.checkBox_33, self.checkBox_34, self.checkBox_35])
        self.draw = self.checkBoxToList([self.checkBox_46, self.checkBox_47, self.checkBox_48, self.checkBox_49, self.checkBox_50])
        self.changeColor = self.checkBoxToList([self.checkBox_36, self.checkBox_37, self.checkBox_38, self.checkBox_39, self.checkBox_40])
        self.threshold = self.spinBox.value()
        if self.path == -1:
            self.warningPopup()

        else :
            try:
                main.main(
                    path=self.path,
                    threshold=self.threshold,
                    right=self.right,
                    left=self.left,
                    showPointer=self.showPointer,
                    draw=self.draw,
                    changeColor=self.changeColor,
                    erase=self.erase
                )
            except:
                self.warningPopup()

    def default(self):
        if self.path == -1:
            self.warningPopup()
        else:
            try:
                main.main(path=self.path)
            except:
                self.warningPopup()

    def checkBoxToList(self, checkBoxList):
        fingerList = []
        for i in range(len(checkBoxList)):
            fingerList.append(int(checkBoxList[i].isChecked()))
        
        return fingerList


    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Home), _translate("MainWindow", "Home"))
        self.groupBox.setTitle(_translate("MainWindow", "Gesture configurations"))
        self.label_9.setText(_translate("MainWindow", "Show pointer :"))
        self.checkBox_31.setText(_translate("MainWindow", "Thumb"))
        self.checkBox_32.setText(_translate("MainWindow", "Index"))
        self.checkBox_33.setText(_translate("MainWindow", "Middle"))
        self.checkBox_34.setText(_translate("MainWindow", "Ring"))
        self.checkBox_35.setText(_translate("MainWindow", "Little"))
        self.label_10.setText(_translate("MainWindow", "Change color :"))
        self.checkBox_36.setText(_translate("MainWindow", "Thumb"))
        self.checkBox_37.setText(_translate("MainWindow", "Index"))
        self.checkBox_38.setText(_translate("MainWindow", "Middle"))
        self.checkBox_39.setText(_translate("MainWindow", "Ring"))
        self.checkBox_40.setText(_translate("MainWindow", "Little"))
        self.label_11.setText(_translate("MainWindow", "Right :"))
        self.checkBox_41.setText(_translate("MainWindow", "Thumb"))
        self.checkBox_42.setText(_translate("MainWindow", "Index"))
        self.checkBox_43.setText(_translate("MainWindow", "Middle"))
        self.checkBox_44.setText(_translate("MainWindow", "Ring"))
        self.checkBox_45.setText(_translate("MainWindow", "Little"))
        self.label_12.setText(_translate("MainWindow", "Draw :"))
        self.checkBox_46.setText(_translate("MainWindow", "Thumb"))
        self.checkBox_47.setText(_translate("MainWindow", "Index"))
        self.checkBox_48.setText(_translate("MainWindow", "Middle"))
        self.checkBox_49.setText(_translate("MainWindow", "Ring"))
        self.checkBox_50.setText(_translate("MainWindow", "Little"))
        self.label_13.setText(_translate("MainWindow", "Left :"))
        self.checkBox_51.setText(_translate("MainWindow", "Thumb"))
        self.checkBox_52.setText(_translate("MainWindow", "Index"))
        self.checkBox_53.setText(_translate("MainWindow", "Middle"))
        self.checkBox_54.setText(_translate("MainWindow", "Ring"))
        self.checkBox_55.setText(_translate("MainWindow", "Little"))
        self.label_14.setText(_translate("MainWindow", "Erase :"))
        self.checkBox_56.setText(_translate("MainWindow", "Thumb"))
        self.checkBox_57.setText(_translate("MainWindow", "Index"))
        self.checkBox_58.setText(_translate("MainWindow", "Middle"))
        self.checkBox_59.setText(_translate("MainWindow", "Ring"))
        self.checkBox_60.setText(_translate("MainWindow", "Little"))
        self.groupBox_3.setTitle(_translate("MainWindow", "GroupBox"))
        self.label_8.setText(_translate("MainWindow", "Threshold :"))
        self.pushButton_2.setText(_translate("MainWindow", "Process"))
        self.pushButton.setText(_translate("MainWindow", "Default"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Configurations"))
        self.menuFiles.setTitle(_translate("MainWindow", "Files"))
        self.actionOpen.setText(_translate("MainWindow", "Open Folder"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))
        self.actionExit.setShortcut(_translate("MainWindow", "Ctrl+Q"))
        self.actionOpen.setShortcut(_translate("MainWindow", "Ctrl+N"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
